name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.ftp_host }}
        user: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_pass }}
        options: "--parallel=10"
